/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_vvlabs_bluetooth_WindowsBluetoothManager */

#ifndef _Included_fr_vvlabs_bluetooth_WindowsBluetoothManager
#define _Included_fr_vvlabs_bluetooth_WindowsBluetoothManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_vvlabs_bluetooth_WindowsBluetoothManager
 * Method:    getDevices
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_fr_vvlabs_bluetooth_WindowsBluetoothManager_getDevices
  (JNIEnv *, jclass);

/*
 * Class:     fr_vvlabs_bluetooth_WindowsBluetoothManager
 * Method:    getDeviceName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fr_vvlabs_bluetooth_WindowsBluetoothManager_getDeviceName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_vvlabs_bluetooth_WindowsBluetoothManager
 * Method:    getDeviceServices
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_fr_vvlabs_bluetooth_WindowsBluetoothManager_getDeviceServices
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fr_vvlabs_bluetooth_WindowsBluetoothManager
 * Method:    getDeviceServiceCharacteristics
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_fr_vvlabs_bluetooth_WindowsBluetoothManager_getDeviceServiceCharacteristics
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     fr_vvlabs_bluetooth_WindowsBluetoothManager
 * Method:    getCharacteristicValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_fr_vvlabs_bluetooth_WindowsBluetoothManager_getCharacteristicValue
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     fr_vvlabs_bluetooth_WindowsBluetoothManager
 * Method:    setCharacteristicValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[B)Z
 */
JNIEXPORT jboolean JNICALL Java_fr_vvlabs_bluetooth_WindowsBluetoothManager_setCharacteristicValue
  (JNIEnv *, jclass, jstring, jstring, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
